name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:         
      - name: Checkout # 获取源码
        uses: actions/checkout@v3 
        with:
          persist-credentials: false

      - name: Install pnpm # 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install and Build # 下载依赖 打包项目
        run: |
          pnpm install
          pnpm run build

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@v4 # 使用别人写好的 actions
        with:  # 自定义环境变量
          BRANCH: gh-pages # github page指定分支
          FOLDER: dist # build后生成的目录
          clean: true
